### ISSUE TITLE
Weird file name behaviour

### ISSUE THREAD

**Issue by Unaimend** [moshi4/ANIclustermap#6]
Hello I have a really weird problem
The folder I use to create the ANI map contains those two species
![image](https://user-images.githubusercontent.com/7808379/219062271-39e28214-35db-4499-8a0c-502f6c8c9311.png)
but they are saved as 
![image](https://user-images.githubusercontent.com/7808379/219062452-c56d3bc7-3cbf-4063-8cdf-45b5770183cd.png).

As you can see the last a is missing.

**Comment by Unaimend** [comment]
This also happens with other species

**Comment by Unaimend** [comment]
![image](https://user-images.githubusercontent.com/7808379/219062680-87738cad-4b7d-43df-8f33-e98841298157.png)

![image](https://user-images.githubusercontent.com/7808379/219062718-97951395-6ce7-4db9-9bc7-40468f28f206.png)

**Comment by Unaimend** [comment]
And it only happens when the species ends with an a

**Comment by Unaimend** [comment]
![image](https://user-images.githubusercontent.com/7808379/219064669-2b1b482f-f167-41ef-b50b-66cdf30f43d6.png)
The plot is also affected

**Comment by moshi4** [comment]
Hi, @Unaimend 

Thank you for reporting the issue.

You are right, indeed, if the last character of the file is `a`, it is unnaturally removed due to the incorrect use of the `rstrip` function below.

https://github.com/moshi4/ANIclustermap/blob/aac49b54ee1012b45a6adefe0f3bb4f56e1978fa/src/aniclustermap/aniclustermap.py#L235

It was my intention to remove only the `.fna` string, but in fact the character ending `.`, `f`, `n`, and `a` were removed.

I will try to release an fixed version by the end of today/tomorrow.

**Comment by Unaimend** [comment]
Thank you very much

**Comment by moshi4** [comment]
A new ANIclustermap v1.2.0 has been released that fixes the bugs raised in this issue.

If you are using pip, you can upgrade with `pip install -U aniclustermap`.
The bioconda version may be released early next week, since the release to bioconda requires some procedures such as review.

I will report back when all the release work is done.

**Comment by moshi4** [comment]
The Bioconda team merged the release earlier than expected. All v1.2.0 release work has been completed.

ANIclustermap is now available for conda as well, so give it a try.

**Comment by Unaimend** [comment]
I can confirm that the big has been fixed. Again, thank you very much
